out_dir: results
metric_best: accuracy
# gpu_mem: True
wandb:
  use: True
  project: actor
  entity: expand-gnns
dataset:
  format: PyG-actor
  name: actor
  task: node
  task_type: classification
  transductive: True
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_num_types: 3
  edge_encoder_name: TypeDictEdge2
  edge_encoder_bn: False
  split_mode: 'standard'
prep:
  exp: True
  exp_deg: 15
  replace_combined_exp_edges: True
train:
  mode: custom_train
  ckpt_best: True
  eval_period: 1
  ckpt_period: 100
model:
  type: Exphormer
  loss_fun: cross_entropy
gt:
  layer_type: Exphormer
  layers: 4
  n_heads: 2
  dim_hidden: 64 
  dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: default
  layers_pre_mp: 1
  layers_post_mp: 1 
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-3
  base_lr: 0.01
  max_epoch: 50
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
