out_dir: results
metric_best: accuracy
gpu_mem: True
wandb:
  use: True
  project: amazon2m
  entity: expand-gnns
dataset:
  format: OGB
  name: ogbn-products
  task: node
  task_type: classification
  transductive: True
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_num_types: 3
  edge_encoder_name: TypeDictEdge2
  edge_encoder_bn: False
  split_mode: 'random'
  split: [0.5, 0.25, 0.25]
prep:
  exp: True
  exp_deg: 15
train:
  mode: custom_train
  ckpt_best: True
  save_attention_scores: True
  eval_period: 1
  ckpt_period: 100
  temp_rdc_ratio: 0.99
  temp_min: 0.05
  temp_wait: 20
model:
  type: Exphormer
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: ASE
  layers: 2
  n_heads: 1
  dim_hidden: 4  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  layer_norm: False
  batch_norm: True
gnn:
  head: default
  layers_pre_mp: 1
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-3
  base_lr: 0.01
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
